version: 2

containers:
  rules:
    - container_name: minecraft-minecraft-1
      keywords:
        - keyword: "Preparing spawn area: 100%"
          title_template: "🎮 Servidor Minecraft ligado"
          message_template: "Você já pode se conectar ao servidor!"

        - keyword: "Server empty for 60 seconds, pausing"
          container_action: stop
          container_action_cooldown: 60
          title_template: "🎮 Servidor Minecraft desligado"
          message_template: "Nenhum jogador online. O servidor foi encerrado."