services:

  minecraft:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    pull_policy: always
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "25565:25565"
    volumes:
      - minecraft_data:/data
    environment:
      EULA: TRUE

      SERVER_NAME: Mine dos Crazy
      MOTD: "Owwwwwwwww §aStoneMask§r..."
      ICON: https://i.scdn.co/image/ab67616d0000b27332ff042034155f8757459ddb

      VERSION: 26.1
      ONLINE_MODE: false
      MAX_PLAYERS: 12
      ENABLE_COMMAND_BLOCK: false
      DIFFICULTY: normal
      PVP: true
      MODE: survival
      LEVEL_TYPE: minecraft:default
      SPAWN_NPCS: true
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS: true
      GENERATE_STRUCTURES: true
      ALLOW_NETHER: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ALLOW_FLIGHT: false
      ENABLE_WHITELIST: true
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 10

      ENABLE_RCON: true
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD:-minedoscrazy}

      MEMORY: 6G
      MAX_MEMORY: 20G
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:ParallelGCThreads=8 -XX:MaxGCPauseMillis=200"
      TZ: America/Sao_Paulo

      TYPE: FABRIC
      FABRIC_FORCE_REINSTALL: true
      MODRINTH_ALLOWED_VERSION_TYPE: alpha
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_PROJECTS: |
        fabric-api
        lithium
        c2me-fabric
        scalablelux
        ferrite-core
        packet-fixer
        disconnect-packet-fix
        vmp-fabric
        krypton
        inventory-management
        alternate-current
        easyauth
        easywhitelist
        luckperms
        vanilla-permissions
    
    labels:
      loggifly.monitor: "true"

      loggifly.keywords.0: "Preparing spawn area: 100%" 
      loggifly.keywords.0.title_template: "🎮 **Servidor de Minecraft ligado!**"
      loggifly.keywords.0.message_template: "Você já pode se conectar ao servidor."

      loggifly.keywords.1: "Server empty for 60 seconds, pausing"
      loggifly.keywords.1.container_action: stop
      loggifly.keywords.1.container_action_cooldown: 60
      loggifly.keywords.1.title_template: "🎮 **Servidor de Minecraft desligado!**"
      loggifly.keywords.1.message_template: "Nenhum jogador online. O servidor foi encerrado automaticamente."

volumes:
  minecraft_data: