services:

  server:
    image: escaping/core-keeper-dedicated:latest
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - server:/home/steam/core-keeper-dedicated
      - data:/home/steam/core-keeper-data
    environment:
      WORLD_NAME: Hora da Pomba
      WORLD_MODE: 0
      MAX_PLAYERS: 10
      PASSWORD: ${SERVER_PASSWORD}
      ACTIVATE_ALL_CONTENT: true

      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      DISCORD_PLAYER_JOIN_ENABLED: false
      DISCORD_PLAYER_LEAVE_ENABLED: false
      DISCORD_SERVER_START_ENABLED: true
      DISCORD_SERVER_START_TITLE: 🟢 Servidor ligado!
      DISCORD_SERVER_START_MESSAGE: Ingresse na partida de ID `$${gameid}` usando a senha `$${password}`.
      DISCORD_SERVER_STOP_ENABLED: true
      DISCORD_SERVER_STOP_TITLE: 🔴 Servidor desligado!
      DISCORD_SERVER_STOP_MESSAGE: Já não é mais possível se conectar ao servidor.

volumes:
  server:
  data: