services:

  server:
    image: ghcr.io/community-valheim-tools/valheim-server:latest
    restart: unless-stopped
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
    volumes:
      - config:/config
      - data:/opt/valheim
    environment:
      SERVER_NAME: Hora da Pomba
      SERVER_PASS: ${SERVER_PASSWORD:-password}
      SERVER_ADDRESS: ${SERVER_ADDRESS:-localhost}
      SERVER_PUBLIC: false
      CROSSPLAY: true
      ADMINLIST_IDS: ${ADMINLIST_IDS:-}
      BACKUPS: false
      PUBLIC_TEST: false
      VALHEIM_PLUS: false
      TZ: America/Sao_Paulo

      DISCORD_WEBHOOK: ${DISCORD_WEBHOOK:-}
      DISCORD_STARTUP_MESSAGE: ':green_circle: **Servidor ligado!** \n Ingresse no mundo `$SERVER_NAME` usando o endereço `$SERVER_ADDRESS` e a senha `$SERVER_PASS`.'
      DISCORD_SHUTDOWN_MESSAGE: ':red_circle: **Servidor desligado!** \n Já não é mais possível se conectar ao servidor.'

      PRE_BOOTSTRAP_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"content\":\"$$(eval echo $$DISCORD_STARTUP_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
      PRE_SERVER_SHUTDOWN_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"content\":\"$$(eval echo $$DISCORD_SHUTDOWN_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
    
volumes:
  config:
  data: