services:

  server:
    image: ghcr.io/community-valheim-tools/valheim-server:latest
    restart: unless-stopped
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
    volumes:
      - config:/config
      - data:/opt/valheim
    environment:
      SERVER_NAME: Hora da Pomba
      SERVER_PASS: ${SERVER_PASSWORD:-password}
      SERVER_ADDRESS: ${SERVER_ADDRESS:-localhost}
      SERVER_PUBLIC: false
      CROSSPLAY: true
      ADMINLIST_IDS: ${ADMINLIST_IDS:-}
      BACKUPS: false
      PUBLIC_TEST: false
      VALHEIM_PLUS: false
      TZ: America/Sao_Paulo

      DISCORD_WEBHOOK: ${DISCORD_WEBHOOK:-}
      PRE_BOOTSTRAP_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"content\":\":green_circle: **Servidor ligado!** \nVocê já pode se conectar ao servidor `$$SERVER_ADDRESS` usando a senha `$$SERVER_PASS`.\"}" "$$DISCORD_WEBHOOK"'
      PRE_SERVER_SHUTDOWN_HOOK: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"content\":\":red_circle: **Servidor desligado!** \nJá não é mais possível se conectar ao servidor.\"}" "$$DISCORD_WEBHOOK"'
    
volumes:
  config:
  data: