services:

  loggifly:
    image: ghcr.io/clemcer/loggifly:v2
    restart: unless-stopped
    pull_policy: always
    environment:
      SYSTEM_NOTIFICATIONS: false
      APPRISE_URL: "${APPRISE_URL:-}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
